swagger:
  service-name: "任务服务"
  service-desc: "管理任务"
flyway:
  table: todo-schema-version
spring:
  profiles.include:
    - swagger
    - flyway
    - rabbit
    - jwt
    - mysql
    - undertow
    - feign
    - hystrix
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
      bindings: # 服务的整合处理
        MESSAGE_QUEUE: # 这个名字是一个通道的名称
          group: logger-event #指定group，确保多个服务实例，消息只被消费一次
          destination: defaultExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置